export const song_list = [
    {
        title: 'КОЛХОЗНИК-КОММУНИСТ',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/DXTVou0oHMLPkFBJSS3xf5c4IP2iyePc',
        time: '2:06',
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'ПЕРЕВОРОТ',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/zOn094BUyzYoK7wxpHE1ShYQn6HQex8c',
        time: '1:49',
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'СТРАНА ДЛЯ ЖЫЦЦЯ',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/OdXgPbkCRRSftjOY5wXtp9sqmLy14e6B',
        time: '1:49',
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'ДОРОГА',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/8tUxGrJhC8QP32vGdzVZC4H57Vx3bFPY',
        time: "2:22",
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'ИДЁТ КОТ!',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/883kFnqhNZMCUWLypt111jWkiSRVJKWK',
        time: "2:22",
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'test',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/883kFnqhNZMCUWLypt111jWkiSRVJKWK',
        time: "2:22",
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'test',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/883kFnqhNZMCUWLypt111jWkiSRVJKWK',
        time: "2:22",
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
    {
        title: 'test',
        artist: 'Лысый Крокодил',
        fileUrl: 'https://audio.jukehost.co.uk/883kFnqhNZMCUWLypt111jWkiSRVJKWK',
        time: "2:22",
        downloadUrl: 'https://drive.google.com/uc?export=download&id=13lrS2rrCNJupCS6SZisf3EPR2atg154U',
    },
  ]